# Generated by Django 3.2.6 on 2021-08-28 23:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer', models.UUIDField()),
                ('product', models.UUIDField()),
            ],
            options={
                'db_table': 'favorite',
            },
        ),
    ]
